version: "3"
services:
  library-management-db:
    image: postgres:15.3
    container_name: library-management-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./postgres-data:/data/test-db
